create table sale
(
	sn               bigint                                not null auto_increment,
    addr_cd          varchar(8)                            not null,
    addr_name        varchar(100)                          not null comment '판매자가 판매하는 지역의 행정구역명',
    seller_id        varchar(25)                           not null,
    seller_nick      varchar(20)                           not null,
    sal_i_cd         varchar(9)                            not null comment '판매 카테고리',
    sal_name         varchar(20)                           not null comment '판매 카테고리명',
    pro_s_cd         varchar(10) default 'S'               null comment 'S:새상품/A:사용감없음/B:사용감적음/C:사용감많음/D:고장파손',
    tx_s_cd          varchar(10) default 'S'               null comment 'Transaction method',
    trade_s_cd_1     varchar(10) default 'F'               null comment 'O:온라인/F:직거래/D:택배거래',
    trade_s_cd_2     varchar(10)                           null comment 'O:온라인/F:직거래/D:택배거래',
    sal_s_cd         varchar(10) default 'S'               null comment 'S:판매중/R:예약중/C:거래완료',
    title            varchar(100)                          not null,
    contents         text                                  not null,
    price            int         default 0                 null,
    biding           char        default 'N'               null comment 'N:미사용/P:가격제시/T:나눔신청',
    pickup_addr_cd   varchar(8)                            null,
    pickup_addr_name varchar(100)                          null,
    detail_addr      text                                  null comment '거래 진행할 상세 장소를 기재',
    brand            varchar(20) default ''                null,
    reg_price        int                                   null,
    tag              varchar(500)                          null comment '배열 형태로 저장',
    buyer_id         varchar(25)                           null,
    buyer_nick       varchar(20)                           null,
    like_cnt         int         default 0                 null comment '사람들이 좋아요 누른 숫자',
    view_cnt         int         default 0                 null,
    r_date           timestamp   default CURRENT_TIMESTAMP null comment '판매글 등록일',
    m_date           timestamp   default CURRENT_TIMESTAMP null comment '판매글 수정일',
    up_cnt           int         default 0                 null comment '작성자가 글을 끌어올린 횟 수',
    hoisting         timestamp                             null comment '판매글 끌어올리기일',
    prop_cnt         int         default 0                 null,
    app_cnt          int         default 0                 null,
    ur_state         char        default 'Y'               null comment 'Y: 사용/N: 삭제',
    ad_state         char        default 'Y'               null comment 'Y: 게시글 유지/N: 게시글 삭제',
    first_r_date     timestamp   default CURRENT_TIMESTAMP null,
    first_idno       varchar(10)                           not null,
    last_r_date      timestamp   default CURRENT_TIMESTAMP null,
    last_idno        varchar(10)                           not null,
    primary key (sn),
    constraint FK_addr_cd_TO_sale_2
        foreign key (seller_id) references user (id),
    constraint FK_administrative_TO_sale_1
        foreign key (addr_cd) references administrative (addr_cd),
    constraint FK_sale_category_TO_sale_1
        foreign key (sal_i_cd) references sale_category (sal_cd)
);

